version: '3.8'

services:
  robowordpress:
    build: .
    ports:
      - "8501:8501"
    environment:
      - WP_URL=${WP_URL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME}
      - CREDENTIALS_FILE=/app/credenciais_google.json
    volumes:
      - ./credenciais_google.json:/app/credenciais_google.json:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
